In [2]:
# Demonstration of TensorFlow and PyTorch
# ----------------------------------------
# AIM: Demonstrate use of TensorFlow and PyTorch by implementing simple code in Python

# 🔹 TensorFlow Section
import tensorflow as tf
import numpy as np

print("=== TensorFlow Demo ===")
# Create random tensors
a = tf.random.uniform((3, 3), minval=1, maxval=10, dtype=tf.int32)
b = tf.random.uniform((3, 3), minval=1, maxval=10, dtype=tf.int32)

print("Tensor A:\n", a.numpy())
print("Tensor B:\n", b.numpy())

# Basic operations
print("\nAddition:\n", tf.add(a, b).numpy())
print("Subtraction:\n", tf.subtract(a, b).numpy())
print("Element-wise Multiplication:\n", tf.multiply(a, b).numpy())
print("Matrix Multiplication:\n", tf.matmul(a, b).numpy())
print("Division:\n", tf.divide(tf.cast(a, tf.float32), tf.cast(b, tf.float32)).numpy())

# Extra operations
print("\nTranspose of A:\n", tf.transpose(a).numpy())
print("Mean of A:", tf.reduce_mean(tf.cast(a, tf.float32)).numpy())
print("Max of B:", tf.reduce_max(b).numpy())

# Broadcasting example
c = tf.constant([1, 2, 3])
print("\nBroadcasted Addition:\n", a + c)

# Reshape and slicing
arr = tf.constant(np.arange(1, 10), shape=(3, 3))
print("\nOriginal Tensor:\n", arr.numpy())
print("Sliced [0:2, 1:3]:\n", arr[0:2, 1:3].numpy())

# Gradient computation
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x**2 + 5*x + 2
grad = tape.gradient(y, x)
print("\nGradient of y = x² + 5x + 2 at x=3:", grad.numpy())
# 🔹 PyTorch Section
import torch

print("\n=== PyTorch Demo ===")
# Create random tensors
A = torch.randint(1, 10, (3, 3))
B = torch.randint(1, 10, (3, 3))

print("Tensor A:\n", A)
print("Tensor B:\n", B)

# Basic operations
print("\nAddition:\n", A + B)
print("Subtraction:\n", A - B)
print("Element-wise Multiplication:\n", A * B)
print("Matrix Multiplication:\n", torch.mm(A, B))
print("Division:\n", A.float() / B.float())

# Extra operations
print("\nTranspose of A:\n", A.T)
print("Mean of A:", A.float().mean().item())
print("Max of B:", B.max().item())

# Broadcasting example
c = torch.tensor([1, 2, 3])
print("\nBroadcasted Addition:\n", A + c)
# Reshape and slicing
C = torch.arange(1, 10).reshape(3, 3)
print("\nOriginal Tensor:\n", C)
print("Sliced [0:2, 1:3]:\n", C[0:2, 1:3])

# Gradient computation
x = torch.tensor(3.0, requires_grad=True)
y = x**2 + 5*x + 2
y.backward()
print("\nGradient of y = x² + 5x + 2 at x=3:", x.grad.item())

=== TensorFlow Demo ===
Tensor A:
 [[5 2 4]
 [9 2 7]
 [4 4 7]]
Tensor B:
 [[3 6 1]
 [4 4 4]
 [8 4 1]]

Addition:
 [[ 8  8  5]
 [13  6 11]
 [12  8  8]]
Subtraction:
 [[ 2 -4  3]
 [ 5 -2  3]
 [-4  0  6]]
Element-wise Multiplication:
 [[15 12  4]
 [36  8 28]
 [32 16  7]]
Matrix Multiplication:
 [[55 54 17]
 [91 90 24]
 [84 68 27]]
Division:
 [[1.6666666  0.33333334 4.        ]
 [2.25       0.5        1.75      ]
 [0.5        1.         7.        ]]

Transpose of A:
 [[5 9 4]
 [2 2 4]
 [4 7 7]]
Mean of A: 4.888889
Max of B: 8

Broadcasted Addition:
 tf.Tensor(
[[ 6  4  7]
 [10  4 10]
 [ 5  6 10]], shape=(3, 3), dtype=int32)

Original Tensor:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced [0:2, 1:3]:
 [[2 3]
 [5 6]]

Gradient of y = x² + 5x + 2 at x=3: 11.0

=== PyTorch Demo ===
Tensor A:
 tensor([[6, 6, 5],
        [9, 4, 3],
        [4, 4, 1]])
Tensor B:
 tensor([[9, 3, 2],
        [7, 9, 7],
        [9, 5, 2]])

Addition:
 tensor([[15,  9,  7],
        [16, 13, 10],
        [13,  9,  3]])
Subtracti