In [5]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable


In [6]:
import tensorflow as tf
import numpy as np

In [8]:
a=tf.constant(20)
b=tf.constant(10)

In [9]:
print(a+b)

tf.Tensor(30, shape=(), dtype=int32)


In [12]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [13]:
rank_1_tensor = tf.constant([5.0, 3.0, 7.0])
print(rank_1_tensor)

tf.Tensor([5. 3. 7.], shape=(3,), dtype=float32)


In [21]:
rank_2_tensor=tf.constant([[1,3],[5,8],[9,4]],dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 3.]
 [5. 8.]
 [9. 4.]], shape=(3, 2), dtype=float16)


In [22]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [24]:
# convert a tensor to a NumPy array either using np.array or the tensor.numpy

In [25]:
np.array(rank_2_tensor)

array([[1., 3.],
       [5., 8.],
       [9., 4.]], dtype=float16)

In [26]:
rank_2_tensor.numpy()

array([[1., 3.],
       [5., 8.],
       [9., 4.]], dtype=float16)

In [ ]:
#addition, element-wise multiplication, and matrix multiplication using tensor

In [27]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 2],
                 [3, 4]])

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32) 



In [28]:
# element-wise addition
print(a + b, "\n") 
# element-wise multiplication
print(a * b, "\n")
# matrix multiplication
print(a @ b, "\n")

tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32) 



In [29]:
c = tf.constant([[3.0, 11.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.math.argmax(c))
# Compute the softmax
#a mathematical function that is used to normalize the values of a given tensor into probabilities.
print(tf.nn.softmax(c))

tf.Tensor(11.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[3.3535014e-04 9.9966466e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [30]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [31]:
tf.reduce_max([1,2,3])

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [32]:
tf.reduce_max(np.array([1,2,3]))

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [34]:
rank_4_tensor = tf.zeros([3, 1, 4, 6])

In [35]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements(3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 1, 4, 6)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 6
Total number of elements(3*2*4*5):  72


In [36]:
tf.rank(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [37]:
tf.rank(rank_3_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [38]:
tf.shape(rank_4_tensor)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 1, 4, 6], dtype=int32)>

In [39]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [42]:
print("First: ",rank_1_tensor[0].numpy())
print("Second: ",rank_1_tensor[1].numpy())
print("Last: ",rank_1_tensor[-1].numpy())

First:  0
Second:  1
Last:  34


In [43]:
print("Everything: ", rank_1_tensor[:].numpy())
print("Before 3: ", rank_1_tensor[:3].numpy())
print("From 4 to the end: ", rank_1_tensor[4:].numpy())
print("From 2, before 6: ", rank_1_tensor[2:6].numpy())
print("Every other item: ", rank_1_tensor[::2].numpy())
print("Reversed: ", rank_1_tensor[::-1].numpy())

Everything:  [ 0  1  1  2  3  5  8 13 21 34]
Before 3:  [0 1 1]
From 4 to the end:  [ 3  5  8 13 21 34]
From 2, before 6:  [1 2 3 5]
Every other item:  [ 0  1  3  8 21]
Reversed:  [34 21 13  8  5  3  2  1  1  0]


In [44]:
print(rank_2_tensor.numpy())

[[1. 3.]
 [5. 8.]
 [9. 4.]]


In [45]:
#Passing an integer for each index, the result is a scalar.

In [46]:
# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1, 1].numpy())

8.0


In [47]:
# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

Second row: [5. 8.]
Second column: [3. 8. 4.]
Last row: [9. 4.]
First item in last column: 3.0
Skip the first row:
[[5. 8.]
 [9. 4.]] 



In [ ]:
#example with a 3-axis tensor

In [48]:
print(rank_3_tensor[:, :, 4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


In [49]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


In [50]:
# You can convert this object into a Python list, too
print(x.shape.as_list())

[3, 1]


In [51]:
# You can reshape a tensor to a new shape.
# Note that you're passing in a list
reshaped = tf.reshape(x, [1, 3])

In [52]:
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


In [53]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
# Assignment 1 
#/*** SAMPLE PROGRAM USING TENSORFLOW**/

In [56]:
a = tf.constant(10)
b = tf.constant(20)

In [57]:
print(a+b)

tf.Tensor(30, shape=(), dtype=int32)


In [58]:
#generates a 1D NumPy array with 100 random numbers, each uniformly distributed between 0 and 1. 
x = np.random.rand(100).astype(np.float32)
print(x)

[0.35398686 0.9430257  0.2395333  0.75424653 0.51113683 0.33073983
 0.17023434 0.6821876  0.8117424  0.10941358 0.41189215 0.60833925
 0.5591483  0.4365905  0.11243573 0.2640859  0.4555108  0.7969536
 0.45117402 0.8182397  0.26026905 0.49838752 0.24028012 0.8092847
 0.33086076 0.1158988  0.70060176 0.10304949 0.08557653 0.5506358
 0.43710473 0.27640027 0.65697473 0.46633297 0.92809355 0.4203198
 0.5899196  0.09836844 0.62217313 0.09054227 0.43201378 0.3542455
 0.7296196  0.56845546 0.5952355  0.26739758 0.43842    0.7462603
 0.58619744 0.96805555 0.13675699 0.4416061  0.12770553 0.27762944
 0.31355134 0.7837286  0.7333791  0.06124573 0.1962897  0.02192496
 0.2529246  0.24575652 0.86295915 0.3196633  0.19846733 0.09322026
 0.5599993  0.6274597  0.53360736 0.689755   0.63824415 0.4957577
 0.28933972 0.6234526  0.16866095 0.7600333  0.65893936 0.46553156
 0.9820237  0.39566863 0.32374498 0.18295568 0.9342351  0.8867852
 0.2571383  0.8825301  0.16425255 0.93606675 0.38709077 0.42901844
 0.

In [61]:
y = x+1

In [62]:
print(y)

[1.3539869 1.9430257 1.2395333 1.7542465 1.5111368 1.3307399 1.1702343
 1.6821876 1.8117424 1.1094136 1.4118922 1.6083393 1.5591483 1.4365904
 1.1124357 1.2640859 1.4555109 1.7969537 1.451174  1.8182397 1.260269
 1.4983876 1.2402802 1.8092847 1.3308607 1.1158988 1.7006018 1.1030495
 1.0855765 1.5506358 1.4371047 1.2764003 1.6569748 1.4663329 1.9280936
 1.4203198 1.5899196 1.0983684 1.6221731 1.0905423 1.4320138 1.3542455
 1.7296196 1.5684555 1.5952356 1.2673976 1.43842   1.7462603 1.5861974
 1.9680555 1.136757  1.441606  1.1277056 1.2776294 1.3135513 1.7837286
 1.7333791 1.0612457 1.1962897 1.021925  1.2529246 1.2457565 1.8629591
 1.3196633 1.1984674 1.0932202 1.5599992 1.6274598 1.5336074 1.689755
 1.6382442 1.4957577 1.2893398 1.6234527 1.168661  1.7600334 1.6589394
 1.4655316 1.9820237 1.3956686 1.323745  1.1829557 1.9342351 1.8867853
 1.2571383 1.8825301 1.1642525 1.9360667 1.3870908 1.4290185 1.2800312
 1.2137284 1.7741492 1.7310162 1.3972696 1.4193501 1.2135161 1.9945029
 1.23850

In [64]:
#used to create a TensorFlow variable W initialized with a single random value drawn from a normal distribution. 
W = tf.Variable(tf.random.normal([1]))

In [65]:
#initializes a TensorFlow variable b with a tensor of shape [1] (a scalar) filled with zeros. 

In [66]:
b = tf.Variable(tf.zeros([1]))

In [67]:
print(b)

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>


In [ ]:
# Create a function for MSE - mean squared error

In [69]:
#This represents a linear model, where W is the weight, x is the input, and b is the bias. 
#The formula W * x + b computes the predicted output (ypred)
def mse_loss():
    ypred = W * x + b
    loss = tf.reduce_mean(tf.square(ypred-y))
    return loss

In [72]:
#creates an instance of the Adam optimizer using TensorFlow's Keras API.

In [73]:
optimizer = tf.keras.optimizers.Adam()

In [76]:
#performing gradient descent optimization using the Adam optimizer to minimize the Mean Squared Error (MSE) 
#loss over 5000 iterations.

# Iterations
for step in range(5000): 
    optimizer.minimize(mse_loss,var_list=[W,b])
    if step % 500 == 0:
        print(step, W.numpy(), b.numpy())

0 [-1.5234426] [0.00099999]
500 [-1.0604693] [0.46123073]
1000 [-0.6772424] [0.8339549]
1500 [-0.37476203] [1.1140524]
2000 [-0.15088758] [1.2981273]
2500 [0.00530021] [1.391795]
3000 [0.11583281] [1.4147682]
3500 [0.20701359] [1.3947845]
4000 [0.29812884] [1.3543626]
4500 [0.39689252] [1.3050157]
